### ISSUE TITLE
Allow "back" interaction via the device.

### ISSUE THREAD

**Issue by MampoX** [dumpus-app/dumpus-app#242] opened 2023-07-21 09:10 UTC
There are buttons to go back on the last page in the app, but when we use the "back" button from our phones, it closes the app, I don't know if this is normal, but it should probably act like the back buttons in the app.

**Comment by Androz2091** [comment] 2023-07-21 10:14
Duplicate of #50

**Closed by Androz2091** 2023-07-21 10:14 UTC
