### ISSUE TITLE
Loading chunk 5971 failed

### ISSUE THREAD

**Issue by Hunam6** [dumpus-app/dumpus-app#305] opened 2023-08-05 22:40 UTC
- First AppStore version
![image](https://github.com/dumpus-app/dumpus-app/assets/38606542/4fd566df-a4a4-4575-869c-11dbf7f7b818)

**Comment by florian-lefebvre** [comment] 2023-08-07 07:42
I don't have a mac to test until Thursday unfortunately. In the meantime, can you share some details:
1. What actions did you do? (like which page, or is it directly after opening)
2. Your iOS version?

**Comment by Androz2091** [comment] 2023-08-07 11:18
Correct me if I'm wrong but:
- iOS is under 16.4
- just before the overview is shown

**Comment by Androz2091** [comment] 2023-08-07 11:19
(that's what he said to me in DMs right after opening the issue)

**Comment by Hunam6** [comment] 2023-08-08 05:30
@Androz2091 you got it right, my precise iOS version is 16.1.2

**Comment by florian-lefebvre** [comment] 2023-08-08 06:34
That's so weird, satori 0.10.2 is installed with the patch but looks like it has no effect. I'll investigate on Thursday

**Comment by florian-lefebvre** [comment] 2023-08-10 09:09
After checking `node_modules/satori/dist/index.js`, I can confirm patch is in the file so it should work. I'll test on ios ASAP

**Comment by florian-lefebvre** [comment] 2023-08-11 09:22
It only happens in prod for some reason :/ will investigate more

**Comment by florian-lefebvre** [comment] 2023-08-11 10:18
It does not happen on web.dumpus.app, safari (ios < 16.4) either 🤔. @Hunam6 can you just confirm your app version?

**Comment by florian-lefebvre** [comment] 2023-08-11 11:09
I think it's caused by https://github.com/vercel/satori/blob/main/src/yoga/index.ts#L19. Trying to fix things with `transpilePackages`

**Comment by Hunam6** [comment] 2023-08-11 14:20
> It does not happen on web.dumpus.app, safari (ios < 16.4) either 🤔. @Hunam6 can you just confirm your app version?

I don't know how to check for app version because I think you've only published one version to the AppStore, but anyway the AppStore doesn't allow any update.

**Comment by florian-lefebvre** [comment] 2023-08-11 14:25
Alright no worries! I'm working on a fix rn 👍

**Comment by florian-lefebvre** [comment] 2023-08-11 15:35
Good news @Hunam6, waiting on #315 to be merged!

**Closed** 2023-08-12 14:14 UTC
Labels: bug, high priority
