### ISSUE TITLE
Overview page has no controls for selecting period for data

### ISSUE THREAD

**Issue by mariusbegby** [dumpus-app/dumpus-app#229] opened 2023-07-20 11:52 UTC
The /overview (https://web.dumpus.app/en/overview/) page has no controls for selecting or displaying the chosen period to display data for.

By default, it is the last 4 weeks. So the overview page shows data for last 4 weeks, **without** indicating to user that it's the last 4 weeks. My suggestions:
- Add controls for choosing and displaying chosen period also in /overview page.

Both the /top and /stats page has this control, so I think it was just forgotten for the /overview page.

Overview page 4 weeks (no controls/indicator):
<img width="806" alt="image" src="https://github.com/dumpus-app/dumpus-app/assets/25694918/bac5487f-f981-422c-abfd-f0dda4d0e48f">

Stats page 4 weeks:
<img width="781" alt="image" src="https://github.com/dumpus-app/dumpus-app/assets/25694918/0408515c-4d91-40f7-8baf-f82f9ce787d6">

Stats page lifetime:
<img width="784" alt="image" src="https://github.com/dumpus-app/dumpus-app/assets/25694918/263ee020-90da-433d-b650-fa785f65511d">

Then going back to overview with lifetime selected(still no indication but you see numbers update):
<img width="776" alt="image" src="https://github.com/dumpus-app/dumpus-app/assets/25694918/bad75849-c245-4e38-9b82-ef868d964250">

**Comment by Androz2091** [comment] 2023-07-20 12:03
![image](https://github.com/dumpus-app/dumpus-app/assets/42497995/fe20926f-edd2-42a1-a5f4-af814e6cea96)
it would look like this
why not

**Comment by Androz2091** [comment] 2023-07-20 12:03
@florian-lefebvre what do you think?

**Comment by Androz2091** [comment] 2023-07-20 12:05
![Capture d’écran 2023-07-20 à 14 05 12](https://github.com/dumpus-app/dumpus-app/assets/42497995/af1af9c0-ddfb-4ac0-9e28-56ed4fc61242)

**Comment by mariusbegby** [comment] 2023-07-20 12:07
@Androz2091 this is just what I was expecting it to look like.

**Comment by florian-lefebvre** [comment] 2023-07-20 13:02
Yeah it was by design originally but I have been thinking about this lately and I think it makes sense to include it on the overview as well. I'm just worried about the bottom nav height taking too much space on overview (nav + time selector + share button)

**Comment by florian-lefebvre** [comment] 2023-07-21 11:51
Closed in favor of #233

**Closed by florian-lefebvre** 2023-07-21 11:51 UTC
Labels: enhancement
